name: My-environment
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - time
  - datetime
  - matplotlib
  - pandas
  - xarray
  
  - dill
  - psutil
  - toolz
  - partd
  - bokeh
  - dask
