name: My-environment
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cartopy
  - jupyter-book
  - jupyterlab
  - matplotlib
  - nc-time-axis
  - netcdf4
  - numpy
  - pip
  - pre-commit
  - dask
  - pyproj
  - pythia-datasets
  - scipy
  - ffmpeg
  - xarray
  - python-graphviz
  - graphviz
